IMPORT THƯ VIỆN VÀ KHỞI TẠO

In [119]:
import numpy as np

In [120]:
data1 = [6, 7.5, 8, 0, 1]

In [121]:
arr1 = np.array(data1)


In [122]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

MẢNG NHIỀU CHIỀU    

In [123]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [124]:
arr2 = np.array(data2)

In [125]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Kiểm tra số chiều của mảng (ndim):

In [126]:
arr2.ndim

2

Kiểm tra hình dạng của mảng (shape):

In [127]:
arr2.shape

(2, 4)

Kiểm tra kiểu dữ liệu của mảng (dtype)

In [128]:
arr1.dtype

dtype('float64')

In [129]:
arr2.dtype

dtype('int64')

CÁC HÀM HỖ TRỢ TẠO MẢNG NHANH

1./ zeros
2./ ones và ones_like
3./ dtype
4./ empty
5./ range và arange
6./ astype

1./ Tạo ra các giá trị trong mảng đều bằng 0

In [130]:
np.zeros(3) #mảng 1 chiều

array([0., 0., 0.])

In [131]:
arr3 = np.zeros(3)
arr3

array([0., 0., 0.])

In [132]:
arr4 = np.zeros((3,3)) #mảng ma trận
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
#các giá trị ma trận đươc tạo ra đều là số thực
arr4.dtype

dtype('float64')

In [134]:
#muốn tạo ra mảng số nguyên thì phải làm thế nào?
arr5 = np.zeros((3,3),dtype=np.int64)
arr5

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [135]:
arr5.dtype

dtype('int64')

2./ Tạo ra các giá trị trong mảng đều bằng 1

In [136]:
arr6 = np.ones((3, 3), dtype=int) #dùng ones thông thường
arr6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [137]:
arr = np.array([[2, 3, 4], [5, 6, 7]], dtype=int) #dùng ones nâng cao
ones_like_arr = np.ones_like(arr)
print(ones_like_arr)
# nó sẽ dựa trên kích thức lẫn kiểu dữ liệu của mảng cũ


[[1 1 1]
 [1 1 1]]


3./ Tạo ra mảng đa chiều 

Ví dụ: mảng 3 chiều (2, 2, 3): Mảng có 2 khối, mỗi khối chứa mảng 2x3.
Cấu trúc của mảng là 3 chiều, có 2 lớp (khối), mỗi khối có 2 hàng và 3 cột.

In [138]:
arr7 = np.empty((2,2,3))
arr7

array([[[0.0e+000, 4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323, 2.5e-323]],

       [[3.0e-323, 3.5e-323, 4.0e-323],
        [4.4e-323, 4.9e-323, 5.4e-323]]])

4./ Hàm range thông thường
Hàm range() trong Python được sử dụng để tạo ra một dãy số nguyên tuần tự, có thể sử dụng để lặp lại trong các vòng lặp for, hoặc có thể được chuyển đổi thành danh sách (list). Đây là một hàm rất cơ bản và thường dùng khi bạn cần một dãy các số nguyên.
Cú pháp: range(start, stop, step)


4.1/ Dùng với dạng vòng lặp

In [139]:
for i in range(1, 10, 2):
    print(i)
#ví dụ in ra các số từ 1 đến sát 10 với bước nhảy là 2

1
3
5
7
9


4.2/ Dùng dưới dạng list(range()).

In [140]:
numbers = list(range(5))
print(numbers)


[0, 1, 2, 3, 4]


5./ Hàm range trong numpy

5.1/ Tạo một mảng với 12 phần tử và sau đó chuyển thành mảng 2x6:

In [141]:
#ví dụ về mảng 2 chiều
arr = np.arange(12).reshape(2, 6)
print(arr)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [142]:
#ví dụ về mảng 3 chiều
arr = np.arange(24).reshape(2, 3, 4)
print(arr)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


6./ Phương thức astype():

Ep kiểu các giá trị phần tử trong mảng này sang mảng khác
+Không thay đổi mảng ban đầu mà tạo ra một bản sao mới với kiểu dữ liệu mới
+Có thể làm mất mát dữ liệu. Ví dụ: float sang int

6.1/ Chuyển mảng int sang float:

In [143]:
arr = np.array([1, 2, 3, 4], dtype=np.int32)
print("Mảng ban đầu:", arr)

arr_float = arr.astype(np.float64)
print("Mảng sau khi chuyển thành số thực:", arr_float)


Mảng ban đầu: [1 2 3 4]
Mảng sau khi chuyển thành số thực: [1. 2. 3. 4.]


6.2/ Chuyển mảng float sang int:

In [144]:
arr = np.array([1.2, 2.5, 3.8, 4.0], dtype=np.float64)
print("Mảng ban đầu:", arr)

arr_int = arr.astype(np.int32)
print("Mảng sau khi chuyển thành số nguyên:", arr_int)

Mảng ban đầu: [1.2 2.5 3.8 4. ]
Mảng sau khi chuyển thành số nguyên: [1 2 3 4]


6.3/ Chuyển kiểu dữ liệu sang boolean

In [145]:
arr = np.array([1, 0, 3, 0])
arr_bool = arr.astype(bool)
print(arr_bool)


[ True False  True False]



OPERATIONS BETWEEN ARRAYS AND SCALARS- Các phép toán giữa Mảng và Số vô hướng


1./ Phép cộng

In [146]:
arr = np.array([1, 2, 3, 4])
result = arr + 10
print(result)


[11 12 13 14]


2./ Phép trừ -> nhân hoặc chia cũng tương tự

In [147]:
result = arr - 2
print(result)


[-1  0  1  2]


3./ Lũy thừa

In [148]:
result = arr ** 2
print(result)


[ 1  4  9 16]


4./ Đối với mảng nhiều chiều thì phép toán cũng thực hiện tương tự

In [149]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
result = arr2d + 10
print(result)


[[11 12 13]
 [14 15 16]]


BASIC INDEXING AND SLICING - THAO TÁC MẢNG BẰNG CHỈ MỤC

1./ Thao tác với mảng 1 chiều

In [150]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Truy cập phần tử đầu tiên
print(arr[2])  # Truy cập phần tử thứ 3
print(arr[-1]) # Truy cập phần tử cuối cùng

10
30
50


2./ Thao tác với mảng nhiều chiều

In [151]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0, 0])  # Phần tử tại hàng 0, cột 0
print(arr2d[1, 2])  # Phần tử tại hàng 1, cột 2
print(arr2d[2, -1]) # Phần tử cuối cùng của hàng 2


1
6
9


3./ Slicing mảng 1 chiều:

In [152]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Lấy các phần tử từ chỉ số 1 đến 3
print(arr[:3])   # Lấy các phần tử từ đầu đến chỉ số 2
print(arr[2:])   # Lấy các phần tử từ chỉ số 2 đến hết
print(arr[::2])  # Lấy các phần tử cách 2 phần tử một lần

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


4./ Slicing mảng nhiều chiều:

In [153]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[:2, 1:3])  # Lấy các phần tử từ hàng 0-1 và cột 1-2
print(arr2d[1:, :2])   # Lấy các phần tử từ hàng 1 đến hết và cột 0-1


[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


5./ Slicing với bước nhảy:

In [154]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[::2])  # Lấy các phần tử cách nhau 2 vị trí


[10 30 50]


6./ Truy cập hoặc sửa đổi từng phần tử thông qua slicing:

In [155]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:4] = 100  # Gán giá trị 100 cho các phần tử từ chỉ số 1 đến 3
print(arr)


[ 10 100 100 100  50]


7./ Slicing mảng là tham chiếu:

Một điểm quan trọng trong NumPy là khi bạn slicing một mảng, bạn sẽ nhận được một tham chiếu đến mảng gốc, không phải là một bản sao. Điều này có nghĩa là khi bạn thay đổi lát cắt, mảng gốc cũng sẽ thay đổi

In [156]:
arr = np.array([1, 2, 3, 4, 5])
slice_arr = arr[1:4]
slice_arr[:] = 10  # Thay đổi tất cả phần tử trong lát cắt
print(arr)  # Mảng gốc cũng thay đổi


[ 1 10 10 10  5]



BOOLEAN INDEXING

Boolean indexing là một cách mạnh mẽ để lọc và truy cập các phần tử trong mảng NumPy dựa trên các điều kiện logic. Với boolean indexing, bạn có thể tạo ra một mảng con chứa các phần tử thỏa mãn điều kiện đã cho

1.1/ Bạn có thể sử dụng một điều kiện để tạo ra một mảng boolean, trong đó mỗi phần tử là True hoặc False tương ứng với việc phần tử trong mảng gốc có thỏa mãn điều kiện hay không.

In [157]:
arr = np.array([1, 2, 3, 4, 5, 6])
bool_arr = arr > 3  # Điều kiện: lớn hơn 3
print(bool_arr)


[False False False  True  True  True]


1.2/ Sau đó, bạn có thể sử dụng mảng boolean này để lấy các phần tử từ mảng gốc mà thỏa mãn điều kiện.

In [158]:
result = arr[bool_arr]
print(result)


[4 5 6]


1.3/ Bạn có thể không cần phải tạo mảng boolean riêng, mà có thể áp dụng trực tiếp điều kiện vào mảng.

In [ ]:
result = arr[arr > 3]  # Lấy tất cả các phần tử lớn hơn 3
print(result)


2./ Kết hợp nhiều điều kiện:

In [ ]:
result = arr[(arr > 2) & (arr < 5)]  # Lấy phần tử lớn hơn 2 và nhỏ hơn 5
print(result)


In [ ]:
result = arr[(arr < 3) | (arr > 5)]  # Lấy phần tử nhỏ hơn 3 hoặc lớn hơn 5
print(result)


In [159]:
result = arr[~(arr > 3)]  # Lấy phần tử không lớn hơn 3 (phủ định của điều kiện arr > 3)
print(result)


[1 2 3]


3./ Boolean indexing cũng hoạt động với mảng nhiều chiều.

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bool_arr2d = arr2d > 5
print(bool_arr2d)


In [ ]:
result = arr2d[bool_arr2d]
print(result)


4./ Thay đổi giá trị với Boolean indexing

In [ ]:
arr[arr > 3] = 99  # Đổi tất cả các phần tử lớn hơn 3 thành 99
print(arr)


5./ HÀM np.where

np.where(condition, x, y)

condition: Điều kiện boolean (True/False). Mảng này sẽ được tạo ra từ một điều kiện nào đó, ví dụ như arr > 3.
x: Giá trị thay thế cho các phần tử thỏa mãn điều kiện (True).
y: Giá trị thay thế cho các phần tử không thỏa mãn điều kiện (False)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.where(arr > 3, 10, arr) #các giá trị lớn hơn 3 thay bằng 10, nếu không phải giữ nguyên
print(result)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.where(arr > 3, 10, -1) #các giá trị lớn hơn 3 thay bằng 10, nếu không phải thay = -1
print(result)


In [160]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
result = np.where(arr2d > 4, 100, arr2d) # cũng hoạt động với mảng 2 chiều
print(result)


[[  1   2   3]
 [  4 100 100]]


Bạn cũng có thể sử dụng np.where để thay thế các giá trị không hợp lệ, chẳng hạn như NaN hoặc inf, bằng giá trị mặc định.

In [161]:
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
result = np.where(np.isnan(arr), 0, arr)
print(result)
#Sử dụng np.isnan(arr) để kiểm tra xem phần tử nào là NaN.
#Các giá trị NaN sẽ được thay bằng 0, còn các giá trị khác giữ nguyên

[1. 2. 0. 4. 0. 6.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.where((arr > 2) & (arr < 5), 20, arr) #kết hợp nhiều điều kiện
print(result)


FANCY INDEXING
Fancy indexing trong NumPy là một phương pháp mạnh mẽ để trích xuất dữ liệu từ mảng bằng cách sử dụng các mảng chỉ số (index arrays). Thay vì sử dụng các chỉ số đơn lẻ hoặc khoảng (slicing) như thông thường, bạn có thể chọn nhiều phần tử cùng một lúc bằng cách cung cấp một danh sách các chỉ số.

In [ ]:
arr = np.arange(10)  # Tạo mảng từ 0 đến 9
print(arr)

# Sử dụng fancy indexing để lấy các phần tử tại chỉ số 1, 3, 5
selected_elements = arr[[1, 3, 5]]
print(selected_elements)

In [ ]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# Chọn phần tử tại vị trí [0, 1], [1, 2], và [2, 0]
result = arr2d[[0, 1, 2], [1, 2, 0]]
print(result)


In [ ]:
arr = np.arange(10)

# Gán giá trị -1 cho các phần tử tại chỉ số 1, 3, 5
arr[[1, 3, 5]] = -1
print(arr)


TRANSPOSING ARRAYS (hoán vị mảng)

Transposing là quá trình hoán đổi các trục của một mảng. Đối với một mảng 2D, nó tương đương với việc hoán đổi hàng thành cột và ngược lại.

1./ Ví dụ về mảng 2D

In [162]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Chuyển vị mảng
arr_transposed = arr.T
print(arr_transposed)

[[1 4]
 [2 5]
 [3 6]]


1.2/ Ví dụ về mảng nhiều chiều 

ối với mảng nhiều chiều (từ 3 chiều trở lên), phương thức .transpose() có thể sắp xếp lại các trục theo bất kỳ thứ tự nào bạn chỉ định.

In [166]:
arr3d = np.arange(1,13).reshape(2, 3, 2)  #lớp,hàng,cột
print(arr3d)
print("-" * 20)
# Chuyển vị mảng theo thứ tự trục mới
arr_transposed = arr3d.transpose(1, 0, 2)
print(arr_transposed)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
--------------------
[[[ 1  2]
  [ 7  8]]

 [[ 3  4]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]
